version: '3.8'

services:
  haproxy:
    build: ./haproxy
    ports:
      - "8080:8080"  # HTTP
      - "8443:8443"  # HTTPS
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - wsupdates_nodejs
      - wsnode1
      - wsnode2
      - wsnode3
    networks:
      - ws_network
    dns:
      - 8.8.8.8
      - 1.1.1.1

  wsupdates_nodejs:
    build: ./wsupdates_nodejs
    environment:
      - DB_PATH=/data/ws.db
      - API_KEY=dev_api_key_123
      - PORT=8000
    volumes:
      - ws_data:/data
    ports:
      - "8000:8000"
    networks:
      - ws_network
    dns:
      - 8.8.8.8
      - 1.1.1.1

  wsnode1:
    build: ./wsnode
    environment:
      - NODE_ID=node1
      - PORT=8081
      - WS_UPDATES_URL=http://wsupdates_nodejs:8000
      - API_KEY=dev_api_key_123
    ports:
      - "8081:8081"
    networks:
      - ws_network
    dns:
      - 8.8.8.8
      - 1.1.1.1

  wsnode2:
    build: ./wsnode
    environment:
      - NODE_ID=node2
      - PORT=8082
      - WS_UPDATES_URL=http://wsupdates_nodejs:8000
      - API_KEY=dev_api_key_123
    ports:
      - "8082:8082"
    networks:
      - ws_network
    dns:
      - 8.8.8.8
      - 1.1.1.1

  wsnode3:
    build: ./wsnode
    environment:
      - NODE_ID=node3
      - PORT=8083
      - WS_UPDATES_URL=http://wsupdates_nodejs:8000
      - API_KEY=dev_api_key_123
    ports:
      - "8083:8083"
    networks:
      - ws_network
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  ws_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254
          aux_addresses:
            dns1: 8.8.8.8
            dns2: 1.1.1.1

volumes:
  ws_data:
